name: checks

on:
  pull_request:
    branches:
      - main

jobs:
  go-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # TODO: use WIP
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CLOUD_GITHUB_ACTION_SERVICE_ACCOUNT }}

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: ./go
          platforms: linux/amd64
          push: false

  go-deadcode:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go/go.mod

      - run: go install golang.org/x/tools/cmd/deadcode@latest

      - run: |
          deadcode -test ./...
          num=$(deadcode -test ./... | wc -l)
          if [ $num -gt 0 ]; then
            exit 1
          fi

  go-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go/go.mod

      - run: go test ./...

  go-vulncheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go/go.mod

      - run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - run: govulncheck ./...

  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_GITHUB_ACTION_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3

      - run: terraform fmt -check -recursive

      - run: terraform init -backend-config="bucket=${{ vars.TERRAFORM_BUCKET }}"

      - run: terraform validate

      - id: vars
        run: |
          git fetch origin main
          echo "label=main-$(git rev-parse --short origin/main)" >> $GITHUB_OUTPUT

      - run: |
          terraform plan \
            -var project_id="${{ vars.PROJECT_ID }}" \
            -var label="${{ steps.vars.outputs.label }}"

  typescript:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: typescript
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "typescript/package.json"
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run build
