name: checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # TODO: use WIP
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CLOUD_GITHUB_ACTION_SERVICE_ACCOUNT }}

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: ./go
          platforms: linux/amd64
          push: false

  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_GITHUB_ACTION_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform fmt -check -recursive

      - run: terraform init -backend-config="bucket=${{ vars.TERRAFORM_BUCKET }}"

      - run: terraform validate

      - id: vars
        run: |
          git fetch origin main
          echo "label=main-$(git rev-parse --short origin/main)" >> $GITHUB_OUTPUT

      - run: |
          terraform plan \
            -var project_id="${{ vars.PROJECT_ID }}" \
            -var label="${{ steps.vars.outputs.label }}"
