name: checks

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_GITHUB_ACTION_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform fmt -check -recursive

      - run: terraform init -backend-config="bucket=${{ vars.TERRAFORM_BUCKET }}"

      - run: terraform validate

      - id: vars
        run: |
          git fetch origin main
          echo "label=main-$(git rev-parse --short origin/main)" >> $GITHUB_OUTPUT

      - run: |
          terraform plan \
            -var project_id="${{ vars.PROJECT_ID }}" \
            -var label="${{ steps.vars.outputs.label }}"
