name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # TODO: use WIP
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CLOUD_GITHUB_ACTION_SERVICE_ACCOUNT }}

      - id: vars
        run: echo "label=${{ env.BRANCH_NAME }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: ./go
          platforms: linux/amd64
          push: true
          tags: europe-west1-docker.pkg.dev/jensravn/cloud-run/jravn:${{ steps.vars.outputs.label }},europe-west1-docker.pkg.dev/jensravn/cloud-run/jravn:latest

  terraform-apply:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_GITHUB_ACTION_SERVICE_ACCOUNT }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init -backend-config="bucket=${{ vars.TERRAFORM_BUCKET }}"

      - id: vars
        run: echo "label=${{ env.BRANCH_NAME }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - run: |
          terraform apply \
            -auto-approve \
            -input=false \
            -var project_id="${{ vars.PROJECT_ID }}" \
            -var label="${{ steps.vars.outputs.label }}"
